version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/pkbs
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD-SHELL", "node healthcheck.js || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

  frontend:
    build: ./frontend
    depends_on:
      - backend

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=pkbs

volumes:
  mongodb_data: